# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: matt schaller
email: mschaller3@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm Matt and I work in the web biz.  I've spent the last 10 years of my life dedicated
  to the web, working with world-class brands such as Hugo Boss, L'Oreal, and
  National Geographic.  I am currently employed by the lovely folks at
  Watsco Inc, where I manage the development of one of their flagship ecommerce 
  platforms.  

  Technical proficiencies include frontend (html/css/js), backend (php,nodejs), data (mysql, mongodb, etl), api (rest/soap), and devops (docker, git, jenkins/travis-ci).  
  Experienced in product management (agile/kanban), team management (internal/agent), and sales engineering.
  Hands on experience with analytics (new relic, ga, coremetric, sitecatalyst), testing (ab/mvt, load).
  
  Hobbies include travel, web, iot, aws, android.

  built with [jekyll](https://github.com/jekyll/jekyll) & [minimal](https://github.com/orderedlist/minimal)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rnatt
github_username:  mattschaller

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
